import React from 'react';
import Navbar from '../../components/Header/Header.jsx';
import './style.css';
const btnenable = () => {
  var checkBox = document.getElementById('tnc');
  var button = document.getElementById('nextbtn');

  if (checkBox.checked == true) {
    button.disabled = false;
  } else {
    button.disabled = true;
  }
};
const bsTerms = () => {
  return (
    <div className={'bstermDiv'}>
      <Navbar />
      <div className={'form-bod'}>
        <h1>SERVICE PARTNER TERMS AND CONDITIONS</h1>
        <div className={'tnc-bod'}>
          <p>
            This document is an electronic record in terms of Information
            Technology Act, 2000 and rules thereunder as applicable and the
            provisions pertaining to electronic records in various statutes as
            amended by the Information Technology Act, 2000. This electronic
            record is generated by a computer system and does not require any
            physical or digital signatures. By clicking on the “I ACCEPT”
            button, You are consenting to be bound by these Service Partner T&C
            for using the ETark SP Platform for the purpose of receiving orders,
            with repairing and servicing electronic devices of the Users. PLEASE
            ENSURE THAT YOU READ AND UNDERSTAND ALL THESE SERVICE PARTNER T&C
            BEFORE YOU USE THE SERVICE OF THE ETARK SP PLATFORM, AS YOU SHALL BE
            BOUND BY ALL THE SERVICE PARTNER T&C CONTAINED HEREIN upon clicking
            on the “I ACCEPT” button. If You do not accept any of the Service
            Partner T&C, please do not use the ETark SP Platform or avail any of
            the services being provided therein. YOUR acceptance TO THE SERVICE
            PARTNER T&C SHALL BE OF BINDING NATURE AND SHALL BE TREATED AS A
            BINDING Contract BETWEEN SERVICE PARTNER AND ETARK IN RESPECT OF THE
            SERVICES OF THE ETARK SP PLATFORM.
          </p>
          <p>
            Your engagement with ETark to use the services of the ETark SP
            Platform are subject to your acceptance of these Service Partner
            T&C. ETark reserves the right, at its sole discretion, to change,
            modify, add or remove these Service Partner T&C, in part or in
            whole, at any time, without prior notice to You. It is Your
            responsibility and duty to check the Service Partner T&C
            periodically for changes. Your continued use of the ETark SP
            Platform following the posting of changes will mean that You accept
            and agree to the changes. As long as You comply with these Service
            Partner T&C, ETark grants You a personal, non-exclusive,
            non-transferable, limited privilege to enter and use the service on
            the ETark SP Platform.
          </p>

          <h2>1. DEFINITIONS</h2>

          <p>
            (i)“Acceptance” means your affirmative action of clicking on the box
            against the words "I Accept” provided at the end of these Service
            Partner T&C, by which action, you unequivocally accept the Service
            Partner T&C and any modifications/alterations thereof;
            <br />
            <br />
            (ii)“Contract” or "Servicing Service Contract" shall mean the
            Electronic Device Servicing Services Contract executed between ETark
            and the Service Partner pursuant to which the Service Partner has
            agreed to undertake Electronic Device Servicing Services;
            <br />
            <br />
            (iii)"ETark Advertisement Contract" shall mean a unique agreement,
            the terms of which may vary from one Service Partner to another
            Service Partner and shall be offered at the discretion of ETark,
            executed between ETark and the Service Partner for allowing the
            latter to host it’s ads, contents or materials for the purpose of
            promoting the business of the Service Partner after taking the
            Service Partner’s consent as far as the ads, contents or materials
            are concerned subjected to certain consideration charged by ETark
            <br />
            <br />
            (iv)“Applicable Law” shall mean and include any law, statute,
            ordinance, rules, regulations, guidelines, policies or other
            pronouncement having the effect of law in India, which is currently
            in effect or which may come in effect on a future date;
            <br />
            <br />
            (v)“ETark” or “ We” or “ Us” or “ Our” shall mean ETark Technology
            Private Limited, a company incorporated under the Companies Act,
            2013 (18 of 2013), and having its registered office at E- 201, Mall
            Enclave, 13 K.B. Sarani, Dum Dum, Kolkata - 700080 which expression
            shall, unless it be repugnant to the context or meaning thereof, be
            deemed to mean and include all our successors, affiliates and
            assigns;
            <br />
            <br />
            (vi)“Service Partner” or “ You” or “ Your” or “ Yourself” shall mean
            individual(s), company including its directors, representatives,
            and/or any other person, LLP/firm, Partnership Firm etc. who has
            executed the Contract for the provision of Electronic Device
            Servicing Services;
            <br />
            <br />
            (vii)“ETark User Platform” or "User Platform" shall mean the User
            facing (interface) Platform of ETark where the User can place an
            order for availing the servicing (including but not limited to
            repairing/recondition/fixing) services. It shall also include the
            user interface where anyone who wishes to Become a Service Partner
            to ETark can do so by clicking a button or choosing the appropriate
            option from the same platform and also any existing Service Partner
            who wishes to update their Service Center details can do so by
            clicking a button or choosing the appropriate option from the same
            platform.
            <br />
            <br />
            (viii)“ETark SP Platform” or "ETark Service Partner Platform" or
            "Service Partner platform" or "SP Platform" shall have the meaning
            assigned to it in the Contract. It shall also include for all
            purposes the user interface provided to the Service Partner wherein
            all the back-end technology is incorporated to enable the Service
            Partner to provide Servicing (including but not limited to
            repairing/recondition/fixing) Services as well as enable ETark, to
            track the orders and other relevant information;
            <br />
            <br />
            (ix)“Order” or “Service Order” shall mean complaints regarding
            Electronic Device(s) owned by the Users which require Servicing
            (including but not limited to repairing/recondition/fixing) Services
            which ETark allocates to Service Centers via it’s SP Platform.
            <br />
            <br />
            (x)"Payment Gateway Provider" or "Payment Partner" shall mean the
            company with which ETark has partnered for carrying out online
            transactions between ETark and the User and ETark and the Service
            Partner. Any transaction of ETark may happen via the Payment Partner
            but not just limited to the Payment Partner and ETark reserves the
            right to change any Payment Partner at any point of time without
            informing the Service Partner;
            <br />
            <br />
            (x)“Service Partner Information” shall mean and may include any
            personal data collected from the Service Partner including “know
            your customer” documents, the Service Partner’s bank details along
            with self-attested copies of valid government issued GST
            Registration Certificate, Business PAN Card, Service Center Address
            Proof, Store Manager’s contact details, location data of Service
            Center, Master Service Agreement with the Device Manufacturing
            company, or any other information that ETark may deem fit, which
            ETark may ask for from the Service Partner at the time of applying
            for becoming a Service Partner through the User Platform or later;
            <br />
            <br />
            (xi)"Electronic Device Manufacturer" or "Device Manufacturer" or
            "Manufacturer" shall mean the company of the Electronic Device of
            the User which the User has requested for Servicing
            (repairing/recondition/fixing) Services at the Service Partner for
            which the Service Partner is authorized to provide Servicing
            (repairing/recondition/fixing) Services.
            <br />
            <br />
            (xii)"Premium Service" shall mean the exclusive revolutionary
            service of ETark where we generate certain instant analysis for the
            User's complaint related to his device and then based on that
            analysis we negotiate with the Manufacturer for a suitable
            compensation for our User due to the problems in his device,
            including but not limited to Payment related, Device malfunctioning
            or Missing item, which may happen even before the Device gets
            physically delivered to any Service Partner or even when the device
            may be out of warranty. The compensation granted could be in the
            form of a Monetary compensation, Free Servicing or a Part/Product
            replacement or certain fraction of it or any other service as deemed
            appropriate by the Manufacturer.
            <br />
            <br />
            (xiii)“Electronic Device Servicing Services” or "Servicing
            (repairing/recondition/fixing) Services" shall mean either or both
            of the following as the context may require: The services provided
            by the Service Partner to ETark of making himself available on the
            ETark SP Platform for the purpose of receiving orders/complaint(s)
            placed by the Users which get allotted automatically by ETark to the
            Available Service Partner nearest to the user's address and
            following the process for making a new entry and updating the status
            of the past entries as is there in the SP platform; The servicing
            (repairing/recondition/fixing) services provided by the Service
            Partner to the Users whereby the Service Partner receives the
            electronic device sent by ETark on behalf of the users and repairs
            the same at the service center so that it can be picked up by ETark
            and returned to the users.
            <br />
            <br />
            (xiv)“Intellectual Property Rights” shall mean and include the
            copyright (whether registered or not), patents including rights of
            filing patents, trademarks, trade names, trade dresses, house marks,
            collective marks, associate marks and the right to register them,
            designs (both industrial and layout), geographical indicators, moral
            rights, broadcasting rights, displaying rights, distribution rights,
            selling rights, reproducing rights, domain names, internet address,
            graphics, artwork, links, information, logos, software,
            configuration, marketing and distribution material and any other
            intellectual property right in the website of ETark, and ETark
            Platform, which are used and/or owned by ETark exclusively;
            <br />
            <br />
            (xv)“Business Development Executive” shall mean a person designated
            by ETark responsible for training and onboarding of a Service
            Partner after verifying the documents post- submission of the
            Contract;
            <br />
            <br />
            (xvi)"Monitoring Executive" shall mean a person designated by ETark
            responsible for providing all necessary operational support that
            such particular Service Partners may require during the time an
            order(s)/complaint(s) gets allocated to a Service Partner on the
            ETark SP Platform, including the payment confirmation to the time it
            gets dispatched from the Service Partner's service center;
            <br />
            <br />
            (xvii)"Sales, After Sales and Grievance Executive" or "SAG
            Executive" shall mean a person designated by ETark to resolve any
            grievance or answer any queries that the Service Center may have
            regarding any order/complaint, post it's completion or Cancellation
            status on the SP Platform;
            <br />
            <br />
            (xviii)“Platform Services” shall have the meaning assigned to it in
            the Contract executed between ETark & respective Service Center(s);
            <br />
            <br />
            (xix)“Termination Date” shall mean the date on which these Service
            Partner T&C and the Contract shall stand terminated and no party
            shall have claim thereafter from either parties;
            <br />
            <br />
            (xx)“Terms and Conditions” or “Service Partner T&C” refers to these
            Service Partner Terms and Conditions, which are available on the
            ETark SP Platform, as may be amended from time to time and the same
            are unconditionally accepted by the Service Partner(s);
            <br />
            <br />
            (xxi)“Logistics Partner” shall mean the logistics executive who
            delivers on behalf of ETark with the unique Order Invoice Number of
            ETark for every order.
            <br />
            <br />
            (xxii)"Non Performance" shall mean the Service Partner rejecting an
            order allotted to him on the SP Platform even before the order is
            physically delivered to him/ declining the servicing
            (repairing/recondition/fixing) services after Inspection of the
            phone at the service center premises before Registering the Order or
            declining the Servicing (repairing/recondition/fixing) services post
            receiving payment for the Service Fee from the User confirmed on
            ETark SP Platform.
          </p>
          <br />
          <br />
          <p>
            Unless the context of these Service Partner T&C otherwise requires:
            <br />
            <br />
            A word or an expression, which denotes a natural person shall
            include an artificial person (and vice versa), any one gender shall
            include the other genders, the singular shall include the plural
            (and vice versa).
            <br />
            <br />
            Heading and bold typeface in these Service Partner T&C are for
            convenience only and shall be ignored for the purposes of
            interpretation.
            <br />
            <br />
            The use of the word “including” followed by a specific example(s) in
            these Service Partner T&C, shall not be construed as limiting the
            meaning of the general wording preceding it.
            <br />
            <br />
            The rule of construction, if any, that a contract should be
            interpreted against the parties responsible for drafting and
            preparation thereof, shall not apply.
            <br />
            <br />
            Reference to any clause, article, section or schedule shall mean a
            reference to a clause, article, section or schedule of these Service
            Partner T&C, unless specified otherwise.
            <br />
            <br />
            Reference to any Applicable Law shall mean a reference to that law
            as amended, consolidated, supplemented or replaced upto date
          </p>
          <h2>2. APPLICABILITY OF SERVICE PARTNER T&C</h2>
          <p>
            These Service Partner T&C together with the Contract shall form the
            complete understanding between the Parties. By accepting these
            Service Partner T&C, You acknowledge and agree to the Service
            Partner T&C and ETark policies that ETark makes applicable to You
            from time to time, to the fullest extent possible.
            <br />
            <br />
            Unless defined herein, the words, phrases and capitalized terms,
            which are contained or referred to in these Service Partner T&C,
            shall be construed as having the meaning thereby attributed to them
            in the Contract.
          </p>
          <h2>3. SERVICE AND CHARGES</h2>
          <p>
            Subject to terms and conditions contained in these Service Partner
            T&C and the Contract, the Service Partner agrees to makes himself
            available on the ETark SP Platform to undertake Servicing Services
            as and when a request for the same is placed through the ETark's SP
            Platform, and to provide Servicing (repairing/recondition/fixing)
            Services to the Users to the best of his abilities and keeping the
            best interest of the Customer
            <br />
            <br />
            Service Partner agrees and acknowledges that upon acceptance of an
            order by the Service Partner, Servicing
            (repairing/recondition/fixing) Services undertaken by him shall
            constitute a separate contract for services under the Consumer
            Protection Act, 2019 or any successor legislations, between the
            Service Partner and the User, to which ETark is not a party.
            <br />
            <br />
            At the time of availing the Platform Services for the first time
            from ETark, the Service Partner shall, at the discretion of ETark,
            be required to pay (i) an onboarding fee (“Onboarding Fee” see
            Annexure A) to ETark of such amount and in such manner as prescribed
            by ETark from time to time, and/or (ii) an interest free refundable
            security deposit (“Security Deposit” see Annexure A) to ETark, of
            such amount and in the manner prescribed by ETark from time to time.
            In addition, ETark shall charge additional fees from the Service
            Partner for any additional training and support services provided by
            ETark (“Training and Support Fees” see Annexure A) to enable the
            Service Partner to render Servicing (repairing/recondition/fixing)
            Services, ETark may provide at its discretion, the Servicing Partner
            with certain assets including, but not limited to, the ETark SP
            Platform on the Service Partner’s smart phone or computer; etc.Upon
            termination of these Service Partner T&C and the Servicing
            (repairing/recondition/fixing) Service Contract, the Security
            Deposit, if any, shall be refunded to the Service Partner by ETark
            only after the assets are returned to ETark in usable
            (same/original) condition. In the event the asset returned by the
            Service Partner is not in usable condition, ETark shall deduct such
            amount as provided in Annexure A hereto. The Parties understand that
            the decision of ETark whether an asset is usable or not shall be
            final and binding on the Service Partner.
            <br />
            <br />
            In consideration of ETark making the ETark SP Platform available to
            You, ETark, at its sole discretion, may charge a fee for providing
            the Platform Services (“Platform Charges” see Annexure A), which
            shall be notified to You by such means as ETark may deem fit. Your
            continuous use of the ETark SP Platform and the Platform Services
            after such notification shall be deemed to be unconditional
            acceptance of the Platform Charges by You. The Platform Charges may
            be revised by ETark, at its discretion, from time to time, without
            any notice.
            <br />
            <br />
            The amount of Training and Support Fees, Onboarding Fee, Security
            Deposit and the Platform Charges shall be determined by ETark and
            may be revised from time to time at the sole discretion of ETark.
            <br />
            <br />
            The Service Partner shall be given sign-in credentials on the ETark
            SP Platform to be able to render Servicing
            (repairing/recondition/fixing) Services. The Service Partner
            acknowledges that the sign-in details, including the username and
            password, are strictly confidential and, accordingly, shall not
            share them with any third party, without written approval/consent
            from ETark.
            <br />
            <br />
            The Service Partner shall have access to the ETark SP Platform at
            all times unless there is a technical glitch or if the ETark SP
            Platform is being updated or is under maintenance. Once logged-in,
            the Service Partner shall remain available and shall be able to
            connect with ETark and the Users for the purpose of receiving
            orders/complaint(s) placed by the Users and undertaking Servicing
            (repairing/recondition/fixing) Services in connection with the same.
            <br />
            <br />
            The Service Partner confirms and acknowledges that by logging-in on
            the ETark SP Platform, he agrees to be monitored by ETark via the
            ETark SP Platform and ETark may share this information with Users on
            a real-time basis for the purpose of enabling the status of the
            Servicing (repairing/recondition/fixing) Services being provided by
            the Service Partner to the Users. The Service Partner further agrees
            that logging-in on the ETark SP Platform shall be deemed
            acceptance/confirmation of the Service Partner’s intention to accept
            orders of ETark's users to render the Servicing Services mentioned
            herein.
            <br />
            <br />
            All reasonable attempts shall be made by the Service Partner to
            receive the order from ETark and service it , as quickly and
            efficiently as possible and to the best interest of the consumer.
            <br />
            <br />
            In consideration for the Servicing Services provided by the Service
            Partner to the Users, the Service Partner may charge the Users a
            service fee, subject to such Service Charges being accepted by the
            User after the Service Partner sends the estimate for the service(s)
            to be done in the form of an Proforma Invoice estimate copy, before
            actually commencing the services, to be sent to the user through the
            ETark SP Platform only. The Service Charges on the basis of the
            Proforma Invoice estimate shall be a ceiling figure of the total
            charge for the service(s) to be done, in the manner provided under
            these Service Partner T&C. After the actual servicing gets done for
            an order, the Service Partner is required to upload the Final
            Invoice copy on the ETark SP platform corresponding to that
            particular order. As the Proforma Invoice estimate is a ceiling
            figure, it will always be more than the estimate as per the Final
            Invoice copy and in the event the Final Invoice value is less than
            the Proforma Invoice estimate, the difference shall be refunded to
            the user through the ETark SP Platform. It is the responsibility of
            the Service Partner to ensure that in both the Proforma Invoice
            estimate and Final Invoice, the values quoted be inclusive of all
            taxes. While receiving payment from the user, ETark shall add the
            maximum Payment gateway charges that could be charged by our Payment
            Gateway Provider for the transaction out of all the different
            payment gateway charges corresponding to the different modes of
            payment so that under any circumstances, the Service Partner
            initially gets the exact amount corresponding to the one raised in
            the Proforma Invoice. In the event the total amount paid by the user
            corresponding to the Pro Forma estimate by the Service Partner and
            the maximum Payment Gateway charges after deduction of charges by
            the Payment gateway Provider is more than the amount quoted by the
            Service Partner, the difference in the amount shall be credited to
            ETark. In the event a user cancels the service fee payment (the
            payment link for the same shall be active at the user's end for 24
            hours from the time the request for the service fee was raised by
            the Service Partner or alternatively the user may decline the
            payment on the payment link through the click of a button at his
            end), the Service Partner could request within 24 hours from the
            time of service fee payment cancellation by the user for the
            Inspection Charges as is applicable pan India as suggested by the
            Device manufacturer and the same would be credited to the Service
            Partner's account. Beyond 24 hours from the time of service fee
            payment cancellation by the user, the Service Partner won't be
            eligible to request for the Inspection Charges as it'll be deemed
            that the Service Partner doesn't want the Inspection charges and in
            such cases ETark won't be responsible for compensating the Service
            Partner in any form.
            <br />
            <br />
            You hereby authorize ETark to facilitate payment for the Servicing
            (repairing/recondition/fixing) services to you which includes
            Service Fee charges or the Inspection Charge from the Users to you
            which shall be remitted to you as soon as the user makes payment on
            the Proforma Invoice sent by you to the User via our SP Platform to
            which the User has 24 hours to make the payment. Once the User makes
            the payment for the Servicing (repairing/recondition/fixing)
            Services of the Service Partner, the transaction for the payment
            shall happen instantly, however there could be settlement period of
            T+1 day as per the Policies of the Payment Gateway Provider of ETark
            and may change from time to time. ETark under no circumstances shall
            be held liable for any delay in payment settlement in the Service
            Partner's bank account once the payment transaction from the User to
            the Service Partner has been confirmed by the Payment Gateway
            Provider of ETark. ETark shall have the right and the obligation to
            pay only such amounts due and payable by ETark to the Service
            Partner, if any amount so remains due and payable after such set
            off, as set out here. Nothing shall prejudice any right or remedy
            available to ETark, whether under contract, law or equity to recover
            any amounts due from, or payable by the Service Partner under or in
            connection with the Contract and the Service Partner T&C, whether
            such amounts arise under contract, tort, statute or equity.
            <br />
            <br />
            Under ETark's Premium Service, in case the compensation offered by
            the manufacturer is Free service or Part/ Product Replacement or a
            monetary compensation or any fraction of these compensations, which
            can be availed only while Servicing the phone by any authorized
            Service Partner, the Service Partner must acknowledge the
            compensation granted by the manufacturer and accordingly waive off
            the equivalent amount from the Proforma Invoice estimate and the
            Final Invoice. The equivalent claim for the waive off in the
            Invoices must be availed by the Service Partner from the
            Manufacturer mentioned in the order who has authorized him to
            provide service by using the written documents/ emails provided by
            the manufacturer to ETark to carry out the same which ETark in turn
            will provide the Service Partner as a sufficient valid proof for the
            same. It'll be the responsibility of the Service Partner to verify
            on its own with the Principal Manufacturer about whether it is
            authorized to provide such waive offs to our Users and if the
            document provided by ETark to avail the same is sufficient enough
            for him to later avail an equivalent claim from the Manufacturer.
            ETark or it's Users won't be liable under any circumstances to
            compensate the Service Partner for the equivalent claim once such
            waive off has been granted by the manufacturer. Such waive off(s)
            shall be solely on account of the service provider and no claim,
            whatsoever, can be brought against ETark in this regard.
            <br />
            <br />
            In order to incentivize the Service Partner for his availability and
            quality and efficient servicing provided by him on the ETark SP
            Platform to undertake Servicing (repairing/recondition/fixing)
            Services, ETark may, at its discretion allow the Service Partner to
            Promote their business by getting featured on ETark user Platform
            for which there would be Advertisement charges levied by ETark and
            the same would be governed as per a separate ETark Advertisement
            Contract, the terms and conditions and consideration of which shall
            be intimated to the Service Partner at that point of time and may
            vary from one Service Partner to another.
            <br />
            <br />
            Notwithstanding anything to the contrary under Clause 3(ix) above,
            During the Servicing (repairing/recondition/fixing) Services, the
            Service Partner shall be shared with the User name, User contact and
            User email ID for the purpose of facilitating audit between the
            Electronic Device Manufacturer and the Service Partner.The same
            shall be be strictly used for the said purpose only as is mentioned
            in the Confidentiality clause, failing which ETark may claim legal
            damages and other charges from the Service Partner for breach of the
            contract which shall be notified to you at that point of time and we
            may also subsequently terminate the Contract and discharging all our
            liabilities towards the Service Center(s).
            <br />
            <br />
            Notwithstanding anything contained in these Service Partner T&C,
            there shall be an obligation on the Service Partner to be available
            on ETark SP Platform for the available timings in a day and the
            available day(s) in a week, as is shared by the Service Partner in
            the ETark SERVICE PARTNER FORM. The Service Partner is required to
            immediately notify ETark about any changes in the Service Partner's
            availability timings in a day and in a week through the Service
            Partner Update Form on the app/ User Platform. ETark shall also not
            supervise the actions and conduct of the Service Partners unless
            they are in gross violation of their duty to render Servicing
            (repairing/recondition/fixing) Services under these Service Partner
            T&C or the Contract. After we receive the submitted form by you and
            verify the details you have provided, you will be put through the
            process of training to use the ETark SP Platform, including but not
            limited to how to receive an order/complain from ETark logistics
            partner or dispatch an order to ETark Logistics partner by our
            Business Development Executive. Any subsequent queries and questions
            raised by the Service Partner after the onboarding will be taken
            care by our Monitoring Executive or our SAG Executive, depending on
            the type of query and the stage at which the concern has been
            raised.
            <br />
            <br />
            You are required to provide the Proforma Invoice Estimate and the
            Final Invoice including all taxes (as under GST Act 2017 or any
            other tax applicable for electronics Item repairing which may arise
            in future) on the ETark SP Platform so that the same could be sent
            to the User for payment. Any form of claim made outside these two
            Invoices (Proforma Invoice Estimate and the Final Invoice) shall not
            be entertained by ETark or our Users at any cost.
          </p>
          <h2>4. OBLIGATIONS OF SERVICE PARTNER</h2>
          <p>
            4.1 Service Partner makes himself/herself available to undertake
            Servicing (repairing/recondition/fixing) Services as and when a
            request for the same is placed by User through the ETark SP
            Platform.
            <br />
            <br />
            4.2 For Accessing our SP Platform, no computer or smartphone or any
            other equipment would be provided by ETark end to the Service
            Partner under any circumstances. (seems contradictory)
            <br />
            <br />
            4.3 For using our SP Platform, the Service Partner needs to update
            the order requests raised on the SP Platform for which ETark won't
            be providing any manpower assistance apart from the Monitoring
            Executives and the SAG Executives who will coordinate and guide in
            the process through telephone and /virtually.
            <br />
            <br />
            4.4 Any expense borne out of operating any computer or smartphone or
            any other equipment to access the online SP Platform such as
            internet costs or manpower costs will be borne by the Service
            Partner(s) .
            <br />
            <br />
            4.5 The Service Partner shall hold and possess a valid Master
            Service Agreement with the Electronic Brand(s) for which he is
            authorized to provide service and is consequently receiving orders
            from ETark and also needs to possess a valid GST Registration
            Certificate and valid Business PAN Card under the Applicable Law for
            his establishment, which are up to date and in subsistence
            throughout the Term of these Service Partner T&C including the
            details of the owner(s). Copies of the Master Service Agreement, GST
            Registration Certificate and Business PAN Card shall be uploaded on
            ETark's Platform after Clicking on "Become a Service Partner" button
            on ETark User Platform before commencing Servicing
            (repairing/recondition/fixing) Services or at any other time deemed
            appropriate by ETark. In the event any of the document expires, it
            shall be the duty of the Service Partner to inform ETark through the
            Update button for Service Partners on our User Platform. ETark will
            not be responsible for any liability whatsoever arising on account
            of the non-compliance of the Service Partner with the Manufacturer
            or the
            <br />
            <br />
            4.6 The Service partner must strive to accept whatever orders are
            assigned to him on the ETark SP Platform which will be visible to
            him along with the device details and the User complaint even before
            the order gets physically delivered to him.
            <br />
            <br />
            4.7 While registering the order post inspection of the device, the
            Service Partner must always quote an estimate in the Proforma
            Invoice which should be greater than the Final Invoice Bill, in
            doing so the Service Partner must keep the value of the Proforma
            Invoice estimate within a reasonable limit (which ETark may state in
            future as deemed appropriate by ETark) above the Final Invoice. Any
            Final Invoice Bill quoted higher than the Proforma Invoice estimate
            shall not be accepted by ETark or the User. Values of the Proforma
            Invoice estimate and the Final Invoice shall be considered valid
            only when the copy of the same is uploaded on the SP Platform.
            <br />
            <br />
            4.8 The Service Partner must ensure that the Proforma Invoice
            estimate and the Final Invoice are prepared as per the guidelines
            and policies of the Electronic Device Manufacturer for whom he is
            authorized to service so that maintain a certain level of parity in
            the pricing against similar servicing (repairing/recondition/fixing)
            services provided by other Service Providers across the state of
            India. In the event ETark observes an anomaly in the prices quoted
            by any Service Partner to the Users for the Servicing
            (repairing/recondition/fixing) services as reflected in the Proforma
            Invoice and the Final Invoice, ETark reserves the right to terminate
            that Service Partner in accordance with the TERMINATION clause.
            <br />
            <br />
            4.9 The Net remuneration for any order serviced by the Service
            Partner coming from ETark SP Platform shall be based on the Final
            Invoice bill and in the event the final Invoice amount is less than
            the Proforma Invoice estimate, the Service Partner must credit the
            difference amount to the User within 7 working days.
            <br />
            <br />
            4.10 The Service Partner must take full liability for the Electronic
            device(s) delivered to him in every order by ETark for which he is
            providing the Servicing (repairing/recondition/fixing) services in
            terms of any sort of hardware (external or internal) or software
            damage from the time the order is delivered to him till the time the
            order is dispatched from the Service Partner's premises. All costs
            borne out of such damages during the period specified must be borne
            by the Service Partner. Under no circumstances ETark shall be liable
            to make any payment with respect to such insurance and ETark shall
            have all the rights to recover any loss, if any, from the payments
            required to be made by ETark to the Service Partner or from the
            security deposit, if any, under the Contract or these Service
            Partner T&C .
            <br />
            <br />
            4.11 For our Premium service users, It'll be the responsibility of
            the Service Partner to verify on its own with the Manufacturer about
            whether it is authorized to provide such waive offs to our Users and
            if the document provided by ETark to avail the same is sufficient
            enough for him to later avail an equivalent claim from the
            Manufacturer. ETark or it's Users won't be liable under any
            circumstances to compensate the Service Partner for the equivalent
            claim once such waive off has been granted by the Service
            Partner.During the course of undertaking Servicing
            (repairing/recondition/fixing) Services, the Service Partner shall
            conduct himself with honesty, discipline and in accordance with the
            policies and instructions of ETark, whether presently in force or
            adopted in the future, including but not limited to safety, quality,
            etc. The Service Partner shall also comply with all Applicable
            Law(s) including the provisions of the Consumer Protection Act, 2019
            and its corresponding rules, amended upto date
            <br />
            <br />
            4.12 Service Partner shall not commit any fraud while providing
            Servicing (repairing/recondition/fixing) Services or otherwise
            commit any act or omission, to gain any undue advantage. Service
            Partner agrees and acknowledges that in case ETark believes that the
            Service Partner has committed any of the foregoing acts, while
            undertaking Servicing (repairing/recondition/fixing) Services, ETark
            shall, in addition to its right to terminate the Contract or Service
            Partner T&C, in its sole discretion reserve the right to (a) disable
            the Service Partner from undertaking Servicing Services through the
            ETark SP Platform for such time as it deems fit and /or (b) deduct
            the undue gain made by the Service Partner through the fraudulent
            orders from the payout and/or the Security Deposit, if any. This
            right to withhold payout including incentives thereof may also be
            exercised by ETark in the event service parameter guidelines, as
            prescribed by the ETark from time to time, if not met.
            <br />
            <br />
            In order to estimate (mitigate) the cost of certain servicing
            (repairing/recondition/fixing) services for calculating our Premium
            service charges to the User and for the purpose of benchmarking the
            cost of the servicing services for each of the Brands of Electronic
            Device Manufacturers that our Service Partners service, ETark may
            ask for a Proforma Invoice Estimate copy for any of the services
            which the Service Partner must oblige with.
            <br />
            <br />
            4.13 All the payments to the Service Partner will be in electronic
            mode unless otherwise specified by ETark from time to time.
            <br />
            <br />
            4.14 The Service Partner shall undertake the Servicing
            (repairing/recondition/fixing) Services by himself and shall not
            delegate the same to any individual or third party at any cost.
            ETark will not be responsible for any liability arising on account
            of the said non-compliance
            <br />
            <br />
            4.15 The welcome kit provided by ETark shall be used in a prudent
            manner, so as not to destroy or damage any of its contents. The
            information shared in the Welcome Kit is confidential and must not
            be shared or revealed to anyone else for whatsoever reasons. Upon
            receiving any order to render Servicing Services after logging-in
            the ETark SP Platform, the Service Partner shall act and perform his
            role in an ethical manner and to the best of his abilities by
            ensuring a timely Servicing. In case of any delays due to device
            parts not available, shortage of staff, lockdown due to COVID etc,
            the Service Partner shall inform the same to our Monitoring
            executive when he reaches out to you. and/or update the same in the
            app.
            <br />
            <br />
            4.16 The Service Partner acknowledges that the goodwill and
            reputation of ETark is at stake with how effectively and efficiently
            the Service Partner renders Servicing (repairing/recondition/fixing)
            Services pursuant to these Service Partner T&C. Accordingly, the
            Service Partner shall not do any act that adversely affects ETark
            and undertakes to be in compliance with Applicable Law at all times
            and shall protect the brand image, business reputation or any other
            asset/property of ETark.
            <br />
            <br />
            4.17 While logged-in the ETark SP Platform, the Service Partner
            shall not engage in any illegal activity or perform any actions that
            are contrary to Applicable Law(s).
            <br />
            <br />
            4.18 The Service Partner is not entitled to claim any reimbursement
            of hospitalization/ hospital bills that may be incurred by the
            Service Partner while rendering Servicing
            (repairing/recondition/fixing) Services or incurred by his family
            members for any unfortunate accidents or severe illness, during the
            subsistence of Contract or Service Partner T&C.
          </p>
          <h2>5. OBLIGATIONS OF ETARK</h2>
          <p>
            5.1 ETark shall endeavor to take reasonable and financially prudent
            measures to ensure sufficient flow of order(s) from Users to the
            Service Partner. However, this endeavour of ETark must not be
            interpreted as an assurance or guarantee for sending service orders
            to the Service Partner.
            <br />
            <br />
            5.2 All Service Partner Information procured shall be kept
            confidential and used only as per these Service Partner T&C and the
            Contract.
            <br />
            <br />
            5.3 ETark shall make all reasonable efforts to ensure that the ETark
            SP Platform is running at all times. However, it shall not be liable
            for any technical glitches or updates/maintenance due to which a
            Service Partner is unable to log-in the ETark SP Platform or receive
            orders.
          </p>
          <h2>6. SERVICE PARTNER INFORMATION</h2>
          <p>
            ETark may collect Service Partner Information at the time of
            execution of these Service Partner T&C or at any time thereafter, to
            establish the identity of the Service Partner.
            <br />
            <br />
            ETark reserves the right to store, process, access and use the
            Service Partner Information for business purposes and needs,
            background check, verification, marketing, service, development,
            analytics, research, and any other purpose as ETark may deem fit and
            in accordance with Applicable Law.
            <br />
            <br />
            The Service Partner hereby expressly consents to such collection and
            use of Service Partner Information.
            <br />
            <br />
            Subject to Applicable Law, ETark may provide to a third party,
            governmental agency, judicial body, any Service Partner Information
            or information relating to Service Partner Services, if there is a
            complaint, dispute or conflict, including any accident involving a
            Service Partner on one hand and ETark, end-consumer, or a third
            party on the other hand;
          </p>
          <h2>7. INTELLECTUAL PROPERTY RIGHTS</h2>
          <p>
            The Parties hereby agree that all Intellectual Property Rights shall
            be in absolute ownership, possession and control of ETark and the
            Service Partner is only permitted to use such Intellectual Property
            Rights in connection with Servicing Services rendered under these
            Service Partner T&C as are specifically permitted by ETark. The
            Parties hereby clarify that no license or rights is granted in the
            Intellectual Property Rights to the Service Partner under these
            Service Partner T&C, by implication or otherwise.
            <br />
            <br />
            Notwithstanding anything contained in these Service Partner T&C, in
            the event the Service Partner uses the Intellectual Property Rights
            in such manner so as to license, sub-license, create derivative
            Intellectual Property Rights, use it otherwise not being in
            connection with Servicing (repairing/recondition/fixing) Services
            rendered under these Service Partner T&C, the same shall constitute
            a breach of these Service Partner T&C and ETark reserves its rights
            to resort to legal proceedings against the Service Partner for
            recovering damages and losses suffered or likely to be suffered.
          </p>
          <h2>8. REPRESENTATIONS AND WARRANTIES</h2>
          <p>
            8.1 The Service Partner represents and warrants as follows:
            <br />
            <br />
            The Service Partner is capable of entering in the present Contract,
            pursuant to the Indian Contract Act, 1872 and is not below the age
            of 18 years as on the Effective Date.
            <br />
            <br />
            All Service Partner Information provided shall be true and correct
            and no information that could impact the Service Partner’s
            performance to render Servicing (repairing/recondition/fixing)
            Services pursuant to these Service Partner T&C and shall not be
            hidden from the ETark anytime during the subsistence of these
            Service Partner T&C.
            <br />
            <br />
            The Service Partner has not been convicted by any court in India or
            any other country of any crimes including but not limited to
            involving moral turpitude. Further, the Service Partner is not a
            party to any pending litigation, which shall materially affect its
            obligations under these Service Partner T&C.
            <br />
            <br />
            8.2 ETark hereby represents and warrants as follows:
            <br />
            <br />
            It is fully capable of executing these Service Partner T&C and
            Servicing Service Contract and has the necessary authority.
            <br />
            <br />
            It shall exercise operational supervision in the form of follow up
            via telephonic calls on the activities of the Service Partner or
            guide the Service Partner to use the SP Platform even though they
            are free to determine how to render Servicing
            (repairing/recondition/fixing) Services as long as they are
            complying with the procedure provided for use of the ETark SP
            Platform, as ETark’s reputation, quality of service and goodwill is
            at stake.
          </p>
          <h2>9. TERMINATION</h2>
          <p>
            9.1 ETark reserves the right to terminate these Service Partner T&C
            and/or the Contract and deny the Service Partner access to ETark SP
            Platform at any time for any reason as it deems fit. The date on
            which the Service Partner’s access to the ETark SP Platform is
            blocked deliberately by ETark shall be considered as the Termination
            Date of these Service Partner T&C and the Contract. The parties
            hereby agree that no claim shall be made pursuant to this clause and
            the same is subject to recovery of damage(s), if any caused to
            ETark.
            <br />
            <br />
            The service center will be removed if at any point of time it is
            adjudicated as insolvent, or has been convicted for any offence or
            has abused his position detrimental to the public interest. Provided
            no service center shall be removed under this clause unless he has
            been given a reasonable opportunity of being heard in the matter.
            <br />
            <br />
            9.2 Without prejudice to the generality of the foregoing clause,
            ETark reserves the right to terminate these Service Partner T&C and
            the Contract with immediate effect for:
            <br />
            <br />
            <ul>
              <li>
                (i) Any breach of the terms of these Service Partner T&C or the
                Contract by the Service Partner;
                <br />
                <br />
                (ii) Failure to verify or authenticate Service Partner
                Information; and
                <br />
                <br />
                (iii) Any action or omission by the Service Partner which can
                cause legal or contractual liability for ETark including but not
                limited to fraudulent conduct, customer complaints, continuous
                unsatisfactory reviews by the Users, misconduct, negligence, and
                all other actions specifically prohibited under Applicable Law.
                <br />
                <br />
              </li>
              <li>
                (iv) ETark is also at liberty to terminate the contract at their
                discretion, where, in their opinion, continuance of the services
                of Service Partner is detrimental to the business interest of
                ETark due to the acts of the Service Partners, such as the
                following:
                <br />
                <br />
                <div className={'abclist'}>
                  (a) Misbehavior, mishandling, rude behavior with the Logistics
                  Partner of ETark, Executives, Users, Other Service partner or
                  any other persons associated with the ETark.
                  <br />
                  <br />
                  (b) Any acts involving criminal offence punishable under law,
                  including physical assault, threatening any of the Staff/
                  Partner of ETark, person associated with ETark and any other
                  persons.
                  <br />
                  <br />
                  (c) Concealment of fact / material information while entering
                  into contract with ETark.
                  <br />
                  <br />
                  (d) Poor & irregular for work, meetings and failure to abide
                  by the rules / terms of contract.
                  <br />
                  <br />
                  (e) Drunk while on duty and drunken behavior.
                  <br />
                  <br />
                  (f) Poor performance for two consecutive weeks. Performance
                  includes - daily productivity, login hour, idle hours, ratio
                  of number of order requests confirmed to the number of order
                  requests allotted, number of ongoing orders, number of orders
                  completed, quality standards such as denying/ fast forwarding/
                  cancelling the order allotted by ETark.
                  <br />
                  <br />
                  (g) Using ETark User's information including his contact
                  details and emails for any purpose other than creating job
                  sheets at the service center of the Service Partner including
                  attempts to contact the User on the personal phone number or
                  email, sharing this information with any third party (apart
                  from the Electronic Device Manufacturer for the purpose of
                  auditing only) who can pose a direct/ indirect competition to
                  ETark or using this information yourself in a manner outside
                  the scope of the Contract or the Service Partner T&Cs.
                  <br />
                  <br />
                  (h) Commission of fraud/ misappropriation/embezzlement for
                  undue monetary gain, which is against the interest of the
                  ETark.
                  <br />
                  <br />
                  (i) Negligence in performing the duty, causing damage of
                  moveable and immoveable assets of ETark, its employees, Users.
                  <br />
                  <br />
                  (j) Indulging in spreading content through digital media,
                  social networking sites, or any other form, which could be
                  detrimental to ETark’s brand and its image.
                  <br />
                  <br />
                  (k) Indulging in acts such as creating ruckus/ strike/ or any
                  activity against ETark, which could be detrimental to the
                  ETark’s brand and its image.
                  <br />
                  <br />
                  (l) Indulging in unauthorized disclosure of Confidential
                  Information of ETark to external agency, person, ETark or
                  organization.
                  <br />
                  <br />
                  (m) Misuse of assets provided by ETark and welcome kits, which
                  could be detrimental to the interest of ETark’s brand and its
                  image.
                  <br />
                  <br />
                  (n) Absconding for more than 4 hours with any asset, Service
                  item, money or any other valuable item belonging to ETark, its
                  employees, Users and/ or other staff member(s).
                  <br />
                  <br />
                  (o) Not responding to ETark's executives over the phone for
                  over 3 hours without appropriate cause during the service
                  timings as provided by the Service Partner himself.
                  <br />
                  <br />
                  (p) Failure to abide by any of the rules and guidelines given
                  by ETark as part of service quality standards and principles.
                  <br />
                  <br />
                  (q) Doing any act unbecoming of a Service Partner.
                  <br />
                  <br />
                  (r) In case the background check, whether wholly or partially,
                  is found unsatisfactory or contrary to the information
                  provided, at any point of time during the term of these
                  Service Partner T&C.
                </div>
              </li>
            </ul>
            <br />
            <br />
            9.3 Upon termination of these Service Partner T&C and the Contract,
            for any devices corresponding to the service orders that are already
            there at the Service Partner’s service center shall be serviced, the
            service fee for which shall be compensated by ETark if already not
            compensated and the service center must handover the same device(s)
            to our Logistics Partner from the same location of the service
            center post the servicing is done. In case the Service Partner fails
            to do so, ETark shall forfeit the Security Deposit (if any) and
            shall institute legal proceedings against you.
            <br />
            <br />
            9.4 Notwithstanding anything contained in this Clause, ETark
            reserves the right to recover any amounts due and owed by the
            Service Partner and take appropriate legal action(s) that may be
            available under Applicable Law and equity for recovery of any such
            amounts due.
            <br />
            <br />
            9.5 In the event, the Service Partner leaves or absconds, the
            provision of Annexure A to these Service Partner T&C shall apply.
            <br />
            <br />
            9.6 In case the Service Partner intends to terminate these Service
            Partner T&C and the Contract on his own, he has to intimate ETark in
            advance by giving at least fifteen (15) days prior notice in
            writing, and/or via. the Update Service Center details button on our
            User Platform his intention to terminate the contract.
            <br />
            <br />
            9.7 In any case the Service Partner is no longer the authorised
            service center according to the electronic device manufacturer due
            to any reason or fraudulently represents that they are authorized
            service center then this contract will be deemed to be terminated.
            <br />
            <br />
            9.8 In case of expiration of the Master Service Agreement of the
            Service Partner with the Manufacturer, leniency will be given by
            ETark to you to renew your contract within 30 days from the
            expiration date of your previous Master Service Agreement with the
            Manufacturer on the condition that you keep ETark informed of the
            developments on the same, failing which you shall be terminated.
            <br />
            <br />
            9.9 In case of an ex Service Partner applying to become a Service
            Partner of ETark, ETark shall factor in the past records of his
            association with ETark along with the details provided by him at
            that point and ETark shall allow him to become a Service Partner at
            its discretion.
          </p>
          <h2>10. COMPLIANCE WITH APPLICABLE LAW</h2>
          <p>
            The Service Partner agrees and consents to comply with all
            Applicable Law(s) at all times while providing the Servicing
            (repairing/recondition/fixing) Services and while accessing the
            ETark SP Platform.
          </p>
          <h2>11. AMENDMENT</h2>
          <p>
            ETark reserves the right to change, modify, reinstate, amend or
            delete any terms and conditions contained in these Service Partner
            T&C, without prior notice, at any time and in its sole discretion,
            by posting a change notice or a new Contract on the ETark SP
            Platform. The Service Partner shall be responsible for keeping
            himself apprised and informed of the revised terms and conditions at
            all times.
          </p>
          <h2>12. RELATIONSHIP OF THE PARTIES</h2>
          <p>
            The Service Partner is an independent business contractor and this
            Service Partner T&C is a principal-to-principal contract. It shall
            not create any partnership, joint venture, employment, agency,
            franchise, sales representative or any vicarious and absolute
            liability relationship between the parties.
            <br />
            <br />
            It is clarified between the parties that neither of the parties
            shall be liable for any action or omission of the other party in any
            manner except for the liabilities so provided under service partner
            T&C(s).
            <br />
            <br />
            It is clearly understood and agreed that under these Service Partner
            T&C no relationship of employer and employee exists between ETark
            and Service Partner.
            <br />
            <br />
            The Service Partner shall not have any claim for permanent
            employment or employment benefits under any statutes / local laws.
          </p>
          <h2>13. INDEMNIFICATION AND LIMITATION OF LIABILITY</h2>
          <p>
            You agree and undertake to indemnify and to hold harmless ETark, its
            affiliates, successors, agents, assigns, and each of their
            directors, officers, employees, associates, agents, and
            representatives or any third party from and against any losses,
            damages, liability, claims, costs, penalty and expenses (including,
            without limitation, reasonable attorneys’ fees) incurred by reason
            of
            <br />
            <br />
            (i) any breach or alleged breach by You of your obligations,
            performance or observance of your role, functions, responsibilities,
            representations, or warranties under the Service Partner T&C and the
            Contract;
            <br />
            <br />
            (ii) any violation of ETark’s policies;
            <br />
            <br />
            (iii) any act or omission that causes or may cause harm to the
            reputation and goodwill of ETark;
            <br />
            <br />
            (iv) any claim of violation of intellectual property of ETark or any
            third party by your usage of Intellectual Property Rights in a
            manner not permitted under the Contract and these Service Partner
            T&C;
            <br />
            <br />
            (v) for any misconduct or unauthorized access or use of the User
            data on the ETark SP Platform or by the transferring of such data to
            any third party or unauthorized disclosure or use of Confidential
            Information of ETark;
            <br />
            <br />
            (vi) any act of theft, fraud, negligence and misconduct by you;
            <br />
            <br />
            (vii) any damage to the Other Service Partner’s or the User’s
            property or any asset; and
            <br />
            <br />
            (viii) any misbehavior towards the Logistics Partner, Users or ETark
            and its employees or tampering with the Electronic Device delivered
            with order while performing the Servicing Services.
            <br />
            <br />
            ETark shall not be liable for any damages or losses incurred in the
            event of waive off granted by the Service Partner on the basis of
            the documents/ email copies provided by ETark where the Manufacturer
            acknowledges to grant certain compensation to the Users. The waive
            off provided by you in the Proforma Invoice estimate and the Final
            invoice in consonance with the document/ email where the
            manufacturer is stating his approval for waive off shall be assumed
            as an understanding between you and the Manufacturer and shall
            happen at your own risk. You shall be liable to indemnify and hold
            ETark harmless against all damages, losses, costs and expenses
            incurred by ETark as a consequence of any complaint from any User
            and/or other Service Partner received by ETark with respect to any
            error or deficiency in the Servicing or any other form of Services.
            <br />
            <br />
            In addition to the indemnification rights of ETark under these
            Service Partner T&C, ETark shall also be entitled to such other
            remedies available under Applicable Law for breach of contract where
            time is of essence.
            <br />
            <br />
            In no event will ETark be liable for any losses arising from or in
            connection with these Service Partner T&C and the Contract, pursuant
            to any claim by the Service Partner against ETark under contract,
            tort or otherwise, if such losses could have been avoided by the
            Service Partner using reasonable efforts to mitigate them. Further,
            the ETark shall also not be liable to the Service Partner in
            contract, tort or otherwise for indirect, special, incidental,
            exemplary, punitive, or consequential damages of any kind whatsoever
            even if advised of the possibility of such damages. Notwithstanding
            anything contrary contained elsewhere in the Contract, the total
            cumulative liability of the ETark to the Service Partner or to any
            person claiming under contract, tort, or otherwise, shall not exceed
            an amount of INR 500/- (Rupees Five hundred only).
            <br />
            <br />
            ETark shall not be responsible or liable for any loss or damage,
            howsoever caused or suffered by the Service Partner arising out of
            the use of the Platform Services offered by the ETark to the Service
            Partner directly or indirectly, for any reason whatsoever, including
            but not limited to damage or loss caused to the Service Partner as a
            result of the Logistics Partner, User’s non-compliance, which
            includes, but is not limited to, any incorrectly placed order
            instructions, malfunction, partial or total failure of any network
            terminal, data processing system, computer tele-transmission or
            telecommunications system or other circumstances whether or not
            beyond the control of ETark or any person or any organization
            involved in the above mentioned systems. Without prejudice to the
            above, ETark shall not be liable for any direct or indirect loss or
            damage, which may be suffered by the Service Partner as a result of
            any failure by the Logistics Partner to show up within any
            stipulated time even if ETark has agreed to such timing or even if
            the Logistics Partner has advised ETark of the possibility that he /
            she may not show up within the stipulated time.
          </p>
          <h2>14. SPECIFIC INDEMNITY</h2>
          <p>
            The Service Partner shall be solely liable for any and all
            accidents/incidents involving the (repairing/recondition/fixing) of
            the electronic device in each order, while providing the Servicing
            (repairing/recondition/fixing) Services. ETark shall not be held
            liable for any such accidents/ incidents involving the Service
            Partner.
          </p>
          <h2>15. SET-OFF</h2>
          <p>
            In addition to any other remedies provided under a contract
            including the Contract and these Service Partner T&C or provided by
            law or in equity, ETark may, at any time, without notice to the
            Service Partner, set off any liability of the Service Partner to
            ETark against any liability of ETark to the Service Partner, whether
            liability is present or future, liquidated or unliquidated, and
            whether or not liability arises under the Contract or these Service
            Partner T&C.
          </p>
          <h2>16. DISPUTE RESOLUTION</h2>
          <p>
            These Service Partner T&C and the Contract shall be governed by laws
            of India.
            <br />
            <br />
            The courts of Kolkata shall have exclusive jurisdiction over all
            disputes arising from these Service Partner T&C and the Contract.
          </p>
          <h2>17. PENALTY</h2>
          <p>
            Notwithstanding anything contrary contained in these Service Partner
            T&C or the Contract, ETark shall reserve a right to charge a penalty
            in case the service partner is found indulging in fraudulent
            activities while providing Servicing Services. The penalty may be
            deducted from the payments made by ETark.
          </p>
          <h2>18. MISCELLANEOUS</h2>
          <p>
            (i) Force Majeure: Neither Party shall have any liability under or
            be deemed to be in breach of these Service Partner T&C or the
            Contract for any delays or failures in performance of these Service
            Partner T&C and the Contract which results from circumstances beyond
            the reasonable control of that Party such as acts of god, fire,
            epidemic/pandemic, earthquake, tempest, flood, lighting, violence of
            any army or mob or enemies of the country.
            <br />
            <br />
            (ii) Assignment: No rights or liabilities under these Service
            Partner T&C and the Contract can be assigned by any of the Parties
            hereto without the prior written consent of the other Party.
            <br />
            <br />
            (iii) Entire Contract: These Service Partner T&C shall be read along
            with the Contract supersedes all prior discussions and Contracts
            (whether oral or written) if any, between the Parties with respect
            to the subject matter of these Service Partner T&C and the Contract.
            <br />
            <br />
            (iv) Term: These Service Partner T&C and the Contract shall, unless
            specifically terminated in accordance with the provisions contained
            herein, be valid and effective from the date of the execution of the
            Contract till such time that the Service Partner continues to remain
            enlisted with the ETark SP Platform.
            <br />
            <br />
            (v) Waiver: No waiver of any part of these Service Partner T&C and
            the Contract or consent to any departure from it by any Party shall
            be effective unless it is in writing. A waiver or consent shall be
            effective only for the purpose for which it is given. No default or
            delay on the part of any Party in exercising any rights, powers or
            privileges operates as a waiver of any right, nor does a single or
            partial exercise of a right exclude others.
            <br />
            <br />
            (vi) Severance: Any provision of these Service Partner T&C and the
            Contract which is invalid or unenforceable shall be ineffective to
            the extent of such invalidity or unenforceability, without affecting
            in any way the validity, legality and enforceability of the
            remaining provisions hereof.
            <br />
            <br />
            ETark retains the right to share the information provided by you
            with any financial lending institution(s) if you agree to the same,
            if it is proved within reason that you have availed a loan from
            them. You forego the right to claim any damages from ETark in the
            event any such financial facility has been availed by you. You also
            agree that ETark will not be liable for any damages arising as a
            result of such disclosure of your information. ETark retains the
            right to withhold pending payouts and terminate you on an immediate
            basis in such cases.
            <br />
            <br />
            Service Partner hereby acknowledges and agrees to the use of his/her
            photographs by ETark for certain purposes, which may include usage
            of the Service Partner's photographs in ETark's internal
            communications and presentations, training materials, marketing and
            advertising activities on various platforms, including without
            limitation, online advertisement, social media and offline
            advertising. Service Partner hereby consent to sharing of his/her
            photographs by ETark with third parties for the aforesaid purposes.
            <br />
            <br />
            The information shared by Service Partner pursuant to this Contract
            shall be used in accordance with the Privacy Policy.
          </p>
          <h2>19. CONFIDENTIALITY</h2>
          <p>
            Other than for provision of Servicing
            (repairing/recondition/fixing)Services by the Service Partner, ETark
            does not share any other information of the Service Partner with
            third parties unless requisitioned by (i) government authorities or
            (ii) the Service Partner, whether orally or in writing (via email,
            SMS etc.) for any purpose whatsoever, including but not limited to
            availing loan from financial institutions, filing of tax returns
            etc.
            <br />
            <br />
            Other than for the purpose of audit between the Manufacturer and the
            Service Services, the Service Partner must not disclose any
            confidential information about ETark, including but not limited to
            these Service Partner T&C, its business strategies, pricing,
            revenues, expenses, User data, and order information to third
            parties.
          </p>
          <h2>20. DISCLAIMER</h2>
          <p>
            ETark does not warrant that You will be able to use the ETark SP
            Platform and/ or will be able to provide the Servicing Services at
            all times on the ETark SP Platform or that the ETark SP Platform and
            the Platform Services will be uninterrupted or error-free or that
            the defects will be capable of being corrected by the ETark in a
            timely fashion. The User Platform Services, ETark SP Platform, the
            output generated there from, and all other technology developed by
            ETark are provided to you on an “AS IS” and “AS AVAILABLE” basis and
            ETark specifically disclaims all warranties and indemnities,
            express, implied or statutory, including without limitation any
            warranty of merchantability, fitness for a particular purpose,
            accuracy, completeness, or any other warranty arising from the
            course of performance or course of dealing.
          </p>
          <p style={{ marginTop: 20, marginBottom: 10 }}>ANNEXURE A</p>
          <p style={{ marginTop: 10, marginBottom: 20 }}>
            At the time of onboarding, Service Partner shall pay :
          </p>

          <p className={'annex'}>
            a) Onboarding Fee: This is a one time non-refundable fee charged by
            ETark to the Service Partner applicable on each service center that
            the Service Partner is on boarding for installing a Service Center
            into ETark SP Platform, the fee of which is prescribed by ETark from
            time to time. At present, this is INR 1000 per service outlet.
          </p>
          <br />
          <br />
          <p className={'annex'}>
            b) Security Deposit: This is a one time interest free refundable fee
            charged by ETark to the Service Partner applicable on each service
            center that the Service Partner is On boarding to provision against
            losses that ETark may suffer in future from any direct or indirect
            damages caused by the Service Partner(subject to the Service Partner
            Terms and Conditions), the fee of which is prescribed by ETark from
            time to time. At present, this is INR 500 per service outlet.
            <span>
              (Refer ten authorized service centre outlets of any brand(s) from
              your city and your security deposit gets waived off. Please make
              sure your service centre name gets mentioned in the form of others
              you refer in order to avail this benefit)
            </span>
          </p>
          <br />
          <br />
          <p className={'annex'}>
            c) Training and Support Fee: This is a one time non-refundable fee
            charged by ETark to the Service Partner applicable on each service
            center that the Service Partner is Onboarding for training the
            Service Partner on how to use the SP Platform and physically doing a
            mock delivery to verify his location, the fee of which is prescribed
            by ETark from time to time. At present, this is INR 200 per service
            outlet.
          </p>
          <br />
          <br />
          <p>
            Post a certain duration of onboarding which can be one month or any
            time period we deems fit, the Service Partner shall pay:
          </p>
          <br />
          <br />
          <p className={'annex'}>
            d) Platform charges : This is a monthly non-refundable fee charged
            by ETark to the Service Partner applicable on each service center
            that he has on boarded on ETark for using the SP platform and the
            Logistics Partner services the fee of which is prescribed by ETark
            from time to time
          </p>
          <br />
          <br />
          <p>
            Service Partner hereby acknowledges and agrees that any amount
            deposited by Service Partner to ETark in the form of Security
            Deposit shall stand forfeited at the sole discretion of ETark, in
            the event Service Partner does not deliver at least one order
            pursuant to the Servicing (repairing/recondition/fixing) Services
            under the Contract for a continuous period of 30 days during the
            term of the Contract.
          </p>
        </div>
        <div className={'tncbtn'}>
          <div className={'radiobtn'}>
            <input
              type="checkbox"
              id="tnc"
              name="tnc"
              value="accept"
              onClick={btnenable}
            />
            <label for="tnc">&nbsp;I accept the above Terms & Conditions</label>
          </div>
          <a href="https://zfrmz.in/QwGcUcFe2BSrbSbWVoro">
            <button id="nextbtn" type="button" disabled>
              Next
            </button>
          </a>
        </div>
      </div>
    </div>
  );
};

export default bsTerms;
