import React from 'react';
import Navbar from '../../components/Header/Header.jsx';
import './style.css';
const btnenable = () => {
  var checkBox = document.getElementById('tnc');
  var button = document.getElementById('nextbtn');

  if (checkBox.checked == true) {
    button.disabled = false;
  } else {
    button.disabled = true;
  }
};
const bsTerms = () => {
  return (
    <div className={'bstermDiv'}>
      <Navbar />
      <div className={'form-bod'}>
        <h1>RETAIL PARTNER TERMS AND CONDITIONS</h1>
        <div className={'tnc-bod'}>
          <p>
            This document is an electronic record in terms of Information
            Technology Act, 2000 and rules thereunder as applicable and the
            provisions pertaining to electronic records in various statutes as
            amended by the Information Technology Act, 2000. This electronic
            record is generated by a computer system and does not require any
            physical or digital signatures. By clicking on the “I ACCEPT”
            button, You are consenting to be bound by these Retail Partner T&C
            for using the ETark RP Platform for the purpose of generating ETark
            Retail Coupons for your customers buying mobile phones of the
            specified brand(s) as communicated by ETark to you. PLEASE ENSURE
            THAT YOU READ AND UNDERSTAND ALL THESE RETAIL PARTNER T&C BEFORE YOU
            USE THE Retail OF THE ETARK RETAIL PLATFORM, AS YOU SHALL BE BOUND
            BY ALL THE RETAIL PARTNER T&C CONTAINED HEREIN upon clicking on the
            “I ACCEPT” button. If You do not accept any of the Retail Partner
            T&C, please do not use the ETark RP Platform or avail any of the
            Retails being provided therein. YOUR acceptance TO THE RETAIL
            PARTNER T&C SHALL BE OF BINDING NATURE AND SHALL BE TREATED AS A
            BINDING Contract BETWEEN RETAIL PARTNER AND ETARK IN RESPECT OF THE
            RetailS OF THE ETARK RP PLATFORM.
          </p>
          <p>
            Your engagement with ETark to use the Retails of the ETark RP
            Platform are subject to your acceptance of these Retail Partner T&C.
            ETark reserves the right, at its sole discretion, to change, modify,
            add or remove these Retail Partner T&C, in part or in whole, at any
            time, without prior notice to You. It is your responsibility and
            duty to check the Retail Partner T&C periodically for changes. Your
            continued use of the ETark RP Platform following the posting of
            changes will mean that You accept and agree to the changes. As long
            as you comply with these Retail Partner T&C, ETark grants You a
            personal, non-exclusive, non-transferable, limited privilege to
            enter and use the Retail on the ETark RP Platform.
          </p>
          <p>
            In the event a Retail Partner contains more than ten Retail center
            outlets, a separate agreement will be formed between ETark and that
            Retail Partner and this agreement shall stand null and void.
          </p>

          <h2>1. DEFINITIONS</h2>
          <p>
            (i)“Acceptance” means your affirmative action of clicking on the box
            against the words "I Accept” provided at the end of these Retail
            Partner T&C, by which action, you unequivocally accept the Retail
            Partner T&C and any modifications/alterations thereof;
            <br />
            <br />
            (ii)“Contract” or "Retail Contract" shall mean the Electronic Device
            Retail Coupon Contract executed between ETark and the Retail Partner
            pursuant to which the Retail Partner has been authorized by ETark to
            issue Retail Coupons on behalf of ETark to the customers, place
            ETark poster at the billing counter of the store and oversee the
            collection of payment for the same by the customer to ETark for the
            customer to avail the services of ETark under the Retail Coupon
            policy of ETark;
            <br />
            <br />
            (iii)"ETark Advertisement Contract" shall mean a unique agreement,
            the terms of which may vary from one Retail Partner to another
            Retail Partner and shall be offered at the discretion of ETark,
            executed between ETark and the Retail Partner for allowing the
            latter to host it’s ads, contents or materials for the purpose of
            promoting the business of the Retail Partner after taking the Retail
            Partner’s consent as far as the ads, contents or materials are
            concerned subjected to certain consideration charged by ETark
            <br />
            <br />
            (iv)“Applicable Law” shall mean and include any law, statute,
            ordinance, rules, regulations, guidelines, policies or other
            pronouncement having the effect of law in India, which is currently
            in effect or which may come in effect on a future date;
            <br />
            <br />
            (v)“ETark” or “We” or “Us” or “Our” shall mean ETark Technology
            Private Limited, a company incorporated under the Companies Act,
            2013 (18 of 2013), and having its registered office at E- 201, Mall
            Enclave, 13 K.B. Sarani, Dum Dum, Kolkata - 700080 which expression
            shall, unless it be repugnant to the context or meaning thereof, be
            deemed to mean and include all our successors, affiliates and
            assigns;
            <br />
            <br />
            (vi)“Retail Partner” or “You” or “Your” or “Yourself” shall mean
            individual(s), company including its directors, representatives,
            and/or any other person, LLP/firm, Partnership Firm etc. who has
            executed the Contract for the provision of Electronic Device
            Servicing Services;
            <br />
            <br />
            (vii)“ETark User Platform” or "User Platform" shall mean the User
            facing (interface) Platform of ETark where the User can place an
            order for availing the servicing (including but not limited to
            repairing/recondition/fixing) services. It shall also include the
            user interface where anyone who wishes to Become a Service Partner
            to ETark can do so by clicking a button or choosing the appropriate
            option from the same platform and also any existing Service Partner
            who wishes to update their Service Center details can do so by
            clicking a button or choosing the appropriate option from the same
            platform. It shall also include the ETark RP Platform.
            <br />
            <br />
            (viii)“ETark RP Platform” or "ETark Retail Partner Platform" or
            "Retail Partner platform" or "RP Platform" shall have the meaning
            assigned to it in the Contract. It shall also include for all
            purposes the user interface provided to the Retail Partner wherein
            all the back-end technology is incorporated to enable the Retail
            Partner to generate Retail Coupons (limited to the Pickup and
            Delivery Service of ETark) as well as enable ETark, to track the
            payment for the Coupons and other relevant information;
            <br />
            <br />
            (ix)“Coupon” or “Retail Coupon” shall mean a certain text code
            applicable to ETark Pickup and Delivery Service sent to the user
            over email issued by the RP which when applied by the user on ETark
            User Platform will make only the Delivery Charge component of the
            Pickup and Delivery service zero.
            <br />
            <br />
            (x) "Payment Partner" shall mean the company with which ETark has
            partnered for carrying out online transactions between ETark and the
            User and ETark and the Retail Partner. Any transaction of ETark may
            happen via the Payment Partner but not just limited to the Payment
            Partner and ETark reserves the right to change any Payment Partner
            at any point of time without informing the Retail Partner;
            <br />
            <br />
            (xi)“Retail Partner Information” shall mean and may include any
            personal data collected from the Retail Partner including “know your
            customer” documents, the Retail Partner’s bank details along with
            self-attested copies of valid government issued GST Registration
            Certificate, Business PAN Card, Retail outlet Address Proof, Store
            Manager’s contact details, location data of Retail outlet, Master
            Authorization certificate with the Device Manufacturing company, or
            any other information that ETark may deem fit, which ETark may ask
            for from the Retail Partner at the time of applying for becoming a
            Retail Partner through the User Platform or later;
            <br />
            <br />
            (xii)"Electronic Device Manufacturer" or "Device Manufacturer" or
            "Manufacturer" shall mean the company of the Electronic Device of
            the User which the User has purchased from the Retail Partner which
            the Retail Partner is authorized to sell.
            <br />
            <br />
            The services provided by the Retail Partner to ETark of making
            himself available on the ETark RP Platform for the purpose of
            generating ETark Retail Coupons for the customers of the Retail
            Partner upon purchase of phones of specified brands;
            <br />
            <br />
            (xiii)“Intellectual Property Rights” shall mean and include the
            copyright (whether registered or not), patents including rights of
            filing patents, trademarks, trade names, trade dresses, house marks,
            collective marks, associate marks and the right to register them,
            designs (both industrial and layout), geographical indicators, moral
            rights, broadcasting rights, diRPlaying rights, distribution rights,
            selling rights, reproducing rights, domain names, internet address,
            graphics, artwork, links, information, logos, software,
            configuration, marketing and distribution material and any other
            intellectual property right in the website of ETark, and ETark
            Platform, which are used and/or owned by ETark exclusively;
            <br />
            <br />
            (xiv)“Business Development Executive” shall mean a person designated
            by ETark responsible for training and onboarding of a Retail Partner
            after verifying the documents post- submission of the Contract;
            <br />
            <br />
            (xv)"Sales, After Sales and Grievance Executive" or "SAG Executive"
            shall mean a person designated by ETark to resolve any grievance or
            answer any queries that the Retail Center may have regarding any
            ETark Retail Coupon, post it's completion or Cancellation status on
            the RP Platform;
            <br />
            <br />
            (xvi)“Platform Services” shall have the meaning assigned to it in
            the Contract executed between ETark & respective Retail Partner
            store(s);
            <br />
            <br />
            (xvii)“Termination Date” shall mean the date on which these Retail
            Partner T&C and the Contract shall stand terminated and no party
            shall have claim thereafter from either parties;
            <br />
            <br />
            (xviii)“Terms and Conditions” or “Retail Partner T&C” refers to
            these Retail Partner Terms and Conditions, which are available on
            the ETark RP Platform, as may be amended from time to time and the
            same are unconditionally accepted by the Retail Partner(s);
            <br />
            <br />
            (xix)"Non Performance" shall mean the Retail Partner not being able
            to sell ETark Coupons to the customer or not maintaining regular
            communication with ETark with regards to the ETark Retail Coupon
            service.
          </p>
          <br />
          <br />
          <p>
            Unless the context of these Retail Partner T&C otherwise requires:
            <br />
            <br />
            A word or an expression, which denotes a natural person shall
            include an artificial person (and vice versa), any one gender shall
            include the other genders, the singular shall include the plural
            (and vice versa).
            <br />
            <br />
            Heading and bold typeface in these Retail Partner T&C are for
            convenience only and shall be ignored for the purposes of
            interpretation.
            <br />
            <br />
            The use of the word “including” followed by a specific example(s) in
            these Retail Partner T&C, shall not be construed as limiting the
            meaning of the general wording preceding it.
            <br />
            <br />
            The rule of construction, if any, that a contract should be
            interpreted against the parties responsible for drafting and
            preparation thereof, shall not apply.
            <br />
            <br />
            Reference to any clause, article, section or schedule shall mean a
            reference to a clause, article, section or schedule of these Retail
            Partner T&C, unless specified otherwise.
            <br />
            <br />
            Reference to any Applicable Law shall mean a reference to that law
            as amended, consolidated, supplemented or replaced upto date
          </p>
          <h2>2. APPLICABILITY OF RETAIL PARTNER T&C</h2>
          <p>
            These Retail Partner T&C together with the Contract shall form the
            complete understanding between the Parties. By accepting these
            Retail Partner T&C, You acknowledge and agree to the Retail Partner
            T&C and ETark policies that ETark makes applicable to You from time
            to time, to the fullest extent possible.
            <br />
            <br />
            Unless defined herein, the words, phrases and capitalized terms,
            which are contained or referred to in these Retail Partner T&C,
            shall be construed as having the meaning thereby attributed to them
            in the Contract.
          </p>
          <h2>3. Retail AND CHARGES</h2>
          <p>
            Subject to terms and conditions contained in these Retail Partner
            T&C and the Contract, the Retail Partner agrees to makes himself
            available on the ETark RP Platform to undertake Retail Coupon
            Services as and when a request for the same is made by the customer
            while purchasing a phone of the specified brand and keeping the best
            interest of the Customer
            <br />
            <br />
            Retail Partner agrees and acknowledges that while generating a ETark
            Retail Coupon at the request of the customer, the Retail Partner
            shall constitute a separate contract for services under the Consumer
            Protection Act, 2019 or any successor legislations, between the
            Retail Partner and the User, to which ETark is not a party.
            <br />
            <br />
            At the time of availing the Platform Services for the first time
            from ETark, ETark may provide at its discretion, the Retail Partner
            with certain assets including, but not limited to, the ETark RP
            Platform on the Retail Partner’s smart phone or computer; etc for
            which ETark may charge a security deposit fee from the Retail
            Partner. Upon termination of these Retail Partner T&C and the Retail
            Coupon Service Contract, the Security Deposit, if any, shall be
            refunded to the Retail Partner by ETark only after the assets are
            returned to ETark in usable (same/original) condition. In the event
            the asset returned by the Retail Partner is not in usable condition,
            ETark shall deduct such amount as provided in Annexure A hereto. The
            Parties understand that the decision of ETark whether an asset is
            usable or not shall be final and binding on the Service Partner.
            <br />
            <br />
            In executing the ETark Retail Coupon services, it shall be the
            responsibility of the Retail Partner to make sure the customer has
            made payment for the Retail Coupon. Generating Coupons of any amount
            with value not equal to the ETark Retail Coupon value (refer to
            Annexure A) shall be considered as null and void. Under such
            circumstances, it shall be the responsibility of the Retail Partner
            to ask the user to make a fresh payment for a ETark Retail Coupon
            value, Issue a fresh ETark Retail Coupon from the RP Platform,
            credit the customer immediately from your own end for the earlier
            coupon value and later reimburse the same from ETark.
            <br />
            <br />
            The Retail Partner shall be given sign-in credentials on the ETark
            RP Platform to be able to render Retail Coupon Services. The Retail
            Partner acknowledges that the sign-in details, including the
            username and password, are strictly confidential and, accordingly,
            shall not share them with any third party, without written
            approval/consent from ETark.
            <br />
            <br />
            The Retail Partner shall have access to the ETark RP Platform at all
            times unless there is a technical glitch or if the ETark RP Platform
            is being updated or is under maintenance. Once logged-in, the Retail
            Partner shall remain available and shall be able to connect with
            ETark for the purpose of issuing ETark Retail Coupons.
            <br />
            <br />
            The Retail Partner confirms and acknowledges that by logging-in on
            the ETark RP Platform, he agrees to be monitored by ETark via the
            ETark RP Platform and ETark may use such information for it’s
            internal analytics purpose. The Retail Partner further agrees that
            logging-in on the ETark RP Platform shall be deemed
            acceptance/confirmation of the Retail Partner’s intention to
            generate Coupons for the Retail Partner’s in house store customers
            to render the Retail Coupon Services mentioned herein.
            <br />
            <br />
            All reasonable attempts shall be made by the Retail Partner to sell
            the ETark Retail Coupon to the customer , as quickly and efficiently
            as possible and to the best interest of the customer.
            <br />
            <br />
            <br />
            In consideration for the Retail Coupon Services provided by the
            Retail Partner to the customers on behalf of ETark, the Retail
            Partner shall be entitled to a certain amount of payment per ETark
            Retail Coupon from ETark (called Retail fee), subject to such Retail
            fee being accepted by the Retail Partner. (Annexure A)
            <br />
            <br />
            <br />
            You hereby authorize ETark to facilitate payment to you for the
            Retail fee due to the ETark Retail Coupon services by you
            collectively on a monthly postpaid basis. Once we make a payment for
            the same to you, the transaction for the payment shall happen
            instantly, however there could be settlement period of T+1 day as
            per the Policies of the Payment Partner of ETark and may change from
            time to time. ETark under no circumstances shall be held liable for
            any delay in payment settlement in the Retail Partner's bank account
            once the payment transaction from the User to the Retail Partner has
            been confirmed by the Payment Partner of ETark. ETark shall have the
            right and the obligation to pay only such amounts due and payable by
            ETark to the Retail Partner, if any amount so remains due and
            payable after such set off, as set out here. Nothing shall prejudice
            any right or remedy available to ETark, whether under contract, law
            or equity to recover any amounts due from, or payable by the Retail
            Partner under or in connection with the Contract and the Retail
            Partner T&C, whether such amounts arise under contract, tort,
            statute or equity.
            <br />
            <br />
            In the event you collect ETark Retail Coupon value from the customer
            through your any payment collection method or account other than the
            one provided by ETark to you or you issue ETark Retail Coupon to the
            customer for any product or brand other than the one specified to
            you by ETark, you shall be liable to appropriate penal action from
            ETark.
            <br />
            <br />
            In order to incentivize the Retail Partner for his availability and
            quality and efficient servicing provided by him on the ETark RP
            Platform to undertake Retail Coupon Services, ETark may, at its
            discretion allow the Retail Partner to Promote their business by
            getting featured on ETark user Platform for which there would be
            Advertisement charges levied by ETark and the same would be governed
            as per a separate ETark Advertisement Contract, the terms and
            conditions and consideration of which shall be intimated to the
            Retail Partner at that point of time and may vary from one Retail
            Partner to another.
            <br />
            <br />
            The ETark Retail Coupon Service shall be applicable only for the
            customers who walk in to the Retail Partner’s outlet. Issuing the
            ETark Retail Coupon for anyone else is strictly prohibited and shall
            be construed as a breach of this contract with appropriate legal
            action.
          </p>
          <h2>4. OBLIGATIONS OF RETAIL PARTNER</h2>
          <p>
            4.1 Service Partner makes himself/herself available to undertake
            Retail Coupon Service as and when a request for the same is
            requested by the customer at the store.
            <br />
            <br />
            4.2 For Accessing our RP Platform, no computer or smartphone or any
            other equipment would be provided from ETark’s end to the Service
            Partner under any circumstances.
            <br />
            <br />
            4.3 For using our RP Platform, the Retail Partner needs to update
            the customer details on the RP Platform for which ETark won't be
            providing any manpower assistance apart from the the SAG Executives
            who will coordinate and guide in the process through telephone and
            /virtually when requested for by the RP.
            <br />
            <br />
            4.4 Any expense borne out of operating any computer or smartphone or
            any other equipment to access the online RP Platform such as
            internet costs or manpower costs will be borne by the Retail
            Partner(s) .
            <br />
            <br />
            4.5 The Retail Partner shall hold and possess a valid GST
            certificate and Business PAN Card and if possible, a valid Master
            Authorization Certificate with the Electronic Brand(s) for which he
            is authorized to sell
            <br />
            <br />
            4.6 While issuing coupons, the Retail Partner must provide the bill
            number for every purchase made on his store in the Coupon ID field
            and make sure the correct customer details are fed into the system.
            An incorrect entry may not allow the customer to avail the Retail
            Coupon on the User Platform.
          </p>
          <h2>5. OBLIGATIONS OF ETARK</h2>
          <p>
            5.1 All Retail Partner Information procured shall be kept
            confidential and used only as per these Retail Partner T&C and the
            Contract.
            <br />
            <br />
            5.2 ETark shall make all reasonable efforts to ensure that the ETark
            RP Platform is running at all times. However, it shall not be liable
            for any technical glitches or updates/maintenance due to which a
            Retail Partner is unable to log-in the ETark RP Platform or receive
            orders.
          </p>
          <h2>6. Retail PARTNER INFORMATION</h2>
          <p>
            ETark may collect Retail Partner Information at the time of
            execution of these Retail Partner T&C or at any time thereafter, to
            establish the identity of the Retail Partner.
            <br />
            <br />
            ETark reserves the right to store, process, access and use the
            Retail Partner Information for business purposes and needs,
            background check, verification, marketing, service, development,
            analytics, research, and any other purpose as ETark may deem fit and
            in accordance with Applicable Law.
            <br />
            <br />
            The Retail Partner hereby expressly consents to such collection and
            use of Retail Partner Information.
            <br />
            <br />
            Subject to Applicable Law, ETark may provide to a third party,
            governmental agency, judicial body, any Retail Partner Information
            or information relating to Retail Partner Services, if there is a
            complaint, dispute or conflict, including any accident involving a
            Retail Partner on one hand and ETark, end-consumer, or a third party
            on the other hand;
          </p>
          <h2>7. INTELLECTUAL PROPERTY RIGHTS</h2>
          <p>
            The Parties hereby agree that all Intellectual Property Rights shall
            be in absolute ownership, possession and control of ETark and the
            Retail Partner is only permitted to use such Intellectual Property
            Rights in connection with Servicing Services rendered under these
            Retail Partner T&C as are specifically permitted by ETark. The
            Parties hereby clarify that no license or rights is granted in the
            Intellectual Property Rights to the Retail Partner under these
            Retail Partner T&C, by implication or otherwise.
            <br />
            <br />
            Notwithstanding anything contained in these Retail Partner T&C, in
            the event the Retail Partner uses the Intellectual Property Rights
            in such manner so as to license, sub-license, create derivative
            Intellectual Property Rights, use it otherwise not being in
            connection with Retail Coupon Services rendered under these Retail
            Partner T&C, the same shall constitute a breach of these Retail
            Partner T&C and ETark reserves its rights to resort to legal
            proceedings against the Retail Partner for recovering damages and
            losses suffered or likely to be suffered.
          </p>
          <h2>8. REPRESENTATIONS AND WARRANTIES</h2>
          <p>
            8.1 The Retail Partner represents and warrants as follows:
            <br />
            <br />
            The Retail Partner is capable of entering in the present Contract,
            pursuant to the Indian Contract Act, 1872 and is not below the age
            of 18 years as on the Effective Date.
            <br />
            <br />
            All Retail Partner Information provided shall be true and correct
            and no information that could impact the Retail Partner’s
            performance to render Retail Coupon Service pursuant to these Retail
            Partner T&C and shall not be hidden from ETark anytime during the
            subsistence of these Retail Partner T&C.
            <br />
            <br />
            The Retail Partner has not been convicted by any court in India or
            any other country of any crimes including but not limited to
            involving moral turpitude. Further, the Retail Partner is not a
            party to any pending litigation, which shall materially affect its
            obligations under these Retail Partner T&C.
            <br />
            <br />
            8.2 ETark hereby represents and warrants as follows:
            <br />
            <br />
            It is fully capable of executing these Retail Partner T&C and ETark
            Retail Coupon Service Contract and has the necessary authority.
            <br />
            <br />
            It shall exercise operational supervision in the form of follow up
            via telephonic calls on the activities of the Retail Partner or
            guide the Retail Partner to use the RP Platform even though they are
            free to determine how to render Retail Coupon Service as long as
            they are complying with the procedure provided for use of the ETark
            RP Platform, as ETark’s reputation, quality of service and goodwill
            is at stake.
          </p>
          <h2>9. TERMINATION</h2>
          <p>
            9.1 ETark reserves the right to terminate these Retail Partner T&C
            and/or the Contract and deny the Retail Partner access to ETark RP
            Platform at any time for any reason as it deems fit. The date on
            which the Retail Partner’s access to the ETark RP Platform is
            blocked deliberately by ETark shall be considered as the Termination
            Date of these Retail Partner T&C and the Contract. The parties
            hereby agree that no claim shall be made pursuant to this clause and
            the same is subject to recovery of damage(s), if any caused to
            ETark.
            <br />
            <br />
            The Retail Partner will be removed if at any point of time it is
            adjudicated as insolvent, or has been convicted for any offence or
            has abused his position detrimental to the public interest. Provided
            no service center shall be removed under this clause unless he has
            been given a reasonable opportunity of being heard in the matter.
            <br />
            <br />
            9.2 Without prejudice to the generality of the foregoing clause,
            ETark reserves the right to terminate these Retail Partner T&C and
            the Contract with immediate effect for:
            <br />
            <br />
            <ul>
              <li>
                (i) Any breach of the terms of these Retail Partner T&C or the
                Contract by the Retail Partner;
                <br />
                <br />
                (ii) Failure to verify or authenticate Retail Partner
                Information; and
                <br />
                <br />
                (iii) Any action or omission by the Retail Partner which can
                cause legal or contractual liability for ETark including but not
                limited to fraudulent conduct, customer complaints, continuous
                unsatisfactory reviews by the Users, misconduct, negligence, and
                all other actions specifically prohibited under Applicable Law.
                <br />
                <br />
              </li>
              <li>
                (iv) ETark is also at liberty to terminate the contract at their
                discretion, where, in their opinion, continuance of the services
                of Retail Partner is detrimental to the business interest of
                ETark due to the acts of the Retail Partners, such as the
                following:
                <br />
                <br />
                <div className={'abclist'}>
                  (a) Misbehavior, mishandling, rude behavior with Executives,
                  Users, Other Retail partner or any other persons associated
                  with the ETark.
                  <br />
                  <br />
                  (b) Any acts involving criminal offence punishable under law,
                  including physical assault, threatening any of the Staff/
                  Partner of ETark, person associated with ETark and any other
                  persons.
                  <br />
                  <br />
                  (c) Concealment of fact / material information while entering
                  into contract with ETark.
                  <br />
                  <br />
                  (d) Poor & irregular for work, meetings and failure to abide
                  by the rules / terms of contract.
                  <br />
                  <br />
                  (f) Poor performance for two consecutive weeks. Performance
                  includes - daily productivity, login hour, idle hours, ratio
                  of number of Retail Coupons generated to the average number of
                  footfalls etc.
                  <br />
                  <br />
                  (g) Sharing customer’s information with any third party (apart
                  from the Electronic Device Manufacturer for the purpose of
                  auditing only) who can pose a direct/ indirect competition to
                  ETark or using this information yourself in a manner outside
                  the scope of the Contract or the Retail Partner T&Cs.
                  <br />
                  <br />
                  (h) Commission of fraud/ misappropriation/embezzlement for
                  undue monetary gain, which is against the interest of the
                  ETark.
                  <br />
                  <br />
                  (i) Negligence in performing the duty, causing damage of
                  moveable and immoveable assets of ETark, its employees, Users.
                  <br />
                  <br />
                  (j) Indulging in spreading content through digital media,
                  social networking sites, or any other form, which could be
                  detrimental to ETark’s brand and its image.
                  <br />
                  <br />
                  (k) Indulging in acts such as creating ruckus/ strike/ or any
                  activity against ETark, which could be detrimental to the
                  ETark’s brand and its image.
                  <br />
                  <br />
                  (l) Indulging in unauthorized disclosure of Confidential
                  Information of ETark to external agency, person, ETark or
                  organization.
                  <br />
                  <br />
                  (m) Misuse of assets provided by ETark and welcome kits, which
                  could be detrimental to the interest of ETark’s brand and its
                  image.
                  <br />
                  <br />
                  (n) Absconding for more than 4 hours with any asset, Service
                  item, money or any other valuable item belonging to ETark, its
                  employees, Users and/ or other staff member(s).
                  <br />
                  <br />
                  (o) Not responding to ETark's executives over the phone for
                  over 4 hours without appropriate cause during the service
                  timings as provided by the Service Partner himself.
                  <br />
                  <br />
                  (p) Failure to abide by any of the rules and guidelines given
                  by ETark as part of service quality standards and principles.
                  <br />
                  <br />
                  (q) Doing any act unbecoming of a Retail Partner.
                  <br />
                  <br />
                  (r) In case the background check, whether wholly or partially,
                  is found unsatisfactory or contrary to the information
                  provided, at any point of time during the term of these Retail
                  Partner T&C.
                </div>
              </li>
            </ul>
            <br />
            <br />
            9.3 Upon termination of these Retail Partner T&C and the Contract,
            for any Issued ETark Retail Coupon after that shall be considered as
            null and void and the Retailer has to settle the dues of the
            customer for the same.
            <br />
            <br />
            9.4 Notwithstanding anything contained in this Clause, ETark
            reserves the right to recover any amounts due and owed by the Retail
            Partner and take appropriate legal action(s) that may be available
            under Applicable Law and equity for recovery of any such amounts
            due.
            <br />
            <br />
            9.5 In the event, the Retal Partner leaves or absconds, the
            provision of Annexure A to these Retail Partner T&C shall apply.
            <br />
            <br />
            9.6 In case the Retail Partner intends to terminate these Retail
            Partner T&C and the Contract on his own, he has to intimate ETark in
            advance by giving at least fifteen (15) days prior notice in
            writing, and/or via. the Update Retail outlet details to terminate
            the contract.
            <br />
            <br />
            9.7 In any case the Retail Partner is no longer the authorised
            retail sellerr according to the electronic device manufacturer due
            to any reason or fraudulently represents that they are authorized
            service center then this contract will be deemed to be terminated.
            <br />
            <br />
            9.8 In case of expiration of the Master Authorization Certificate of
            the Retail Partner with the Manufacturer, leniency will be given by
            ETark to you to renew your contract within 30 days from the
            expiration date of your previous Master Authorization Certificate
            with the Manufacturer on the condition that you keep ETark informed
            of the developments on the same, failing which you shall be
            terminated.
            <br />
            <br />
            9.9 In case of an ex Retail Partner applying to become a Retail
            Partner of ETark, ETark shall factor in the past records of his
            association with ETark along with the details provided by him at
            that point and ETark shall allow him to become a Retail Partner at
            its discretion.
          </p>
          <h2>10. COMPLIANCE WITH APPLICABLE LAW</h2>
          <p>
            The Retail Partner agrees and consents to comply with all Applicable
            Law(s) at all times while providing the ETark Retail Coupon services
            and while accessing the ETark RP Platform.
          </p>
          <h2>11. AMENDMENT</h2>
          <p>
            ETark reserves the right to change, modify, reinstate, amend or
            delete any terms and conditions contained in these Retail Partner
            T&C, without prior notice, at any time and in its sole discretion,
            by posting a change notice or a new Contract on the ETark RP
            Platform. The Retail Partner shall be responsible for keeping
            himself apprised and informed of the revised terms and conditions at
            all times.
          </p>
          <h2>12. RELATIONSHIP OF THE PARTIES</h2>
          <p>
            The Retail Partner is an independent business contractor and this
            Retail Partner T&C is a principal-to-principal contract. It shall
            not create any partnership, joint venture, employment, agency,
            franchise, sales representative or any vicarious and absolute
            liability relationship between the parties.
            <br />
            <br />
            It is clarified between the parties that neither of the parties
            shall be liable for any action or omission of the other party in any
            manner except for the liabilities so provided under service partner
            T&C(s).
            <br />
            <br />
            It is clearly understood and agreed that under these Retail Partner
            T&C no relationship of employer and employee exists between ETark
            and Retail Partner.
            <br />
            <br />
            The Retail Partner shall not have any claim for permanent employment
            or employment benefits under any statutes / local laws.
          </p>
          <h2>13. INDEMNIFICATION AND LIMITATION OF LIABILITY</h2>
          <p>
            You agree and undertake to indemnify and to hold harmless ETark, its
            affiliates, successors, agents, assigns, and each of their
            directors, officers, employees, associates, agents, and
            representatives or any third party from and against any losses,
            damages, liability, claims, costs, penalty and expenses (including,
            without limitation, reasonable attorneys’ fees) incurred by reason
            of
            <br />
            <br />
            (i) any breach or alleged breach by You of your obligations,
            performance or observance of your role, functions, responsibilities,
            representations, or warranties under the Retail Partner T&C and the
            Contract;
            <br />
            <br />
            (ii) any violation of ETark’s policies;
            <br />
            <br />
            (iii) any act or omission that causes or may cause harm to the
            reputation and goodwill of ETark;
            <br />
            <br />
            (iv) any claim of violation of intellectual property of ETark or any
            third party by your usage of Intellectual Property Rights in a
            manner not permitted under the Contract and these Retail Partner
            T&C;
            <br />
            <br />
            (v) for any misconduct or unauthorized access or use of the User
            data on the ETark RP Platform or by the transferring of such data to
            any third party or unauthorized disclosure or use of Confidential
            Information of ETark;
            <br />
            <br />
            (vi) any act of theft, fraud, negligence and misconduct by you;
            <br />
            <br />
            (vii) any damage to the Other Retail Partner’s or the User’s
            property or any asset; and
            <br />
            <br />
            (viii) any misbehavior towards customers or ETark and its employees
            while performing the Retail Coupon services.
            <br />
            <br />
            ETark shall not be liable for any damages or losses incurred by the
            customer in the event of non generation of Retail Coupon by the RP.
            <br />
            <br />
            In addition to the indemnification rights of ETark under these
            Retail Partner T&C, ETark shall also be entitled to such other
            remedies available under Applicable Law for breach of contract where
            time is of essence.
            <br />
            <br />
            In no event will ETark be liable for any losses arising from or in
            connection with these Retail Partner T&C and the Contract, pursuant
            to any claim by the Retail Partner against ETark under contract,
            tort or otherwise, if such losses could have been avoided by the
            Retail Partner using reasonable efforts to mitigate them. Further,
            the ETark shall also not be liable to the Retail Partner in
            contract, tort or otherwise for indirect, special, incidental,
            exemplary, punitive, or consequential damages of any kind whatsoever
            even if advised of the possibility of such damages. Notwithstanding
            anything contrary contained elsewhere in the Contract, the total
            cumulative liability of the ETark to the Retail Partner or to any
            person claiming under contract, tort, or otherwise, shall be zero..
            <br />
            <br />
          </p>
          <h2>14. SPECIFIC INDEMNITY</h2>
          <p>
            The Retail Partner shall be collecting payment from the customer on
            behalf of ETark and issuing the Retail Coupon as part of the
            agreement, failing in either of these activities shall be construed
            as failure of the duties of the Retail Partner.
          </p>
          <h2>15. SET-OFF</h2>
          <p>
            In addition to any other remedies provided under a contract
            including the Contract and these Retail Partner T&C or provided by
            law or in equity, ETark may, at any time, without notice to the
            Retail Partner, set off any liability of the Retail Partner to ETark
            against any liability of ETark to the Retail Partner, whether
            liability is present or future, liquidated or unliquidated, and
            whether or not liability arises under the Contract or these Retail
            Partner T&C.
          </p>
          <h2>16. DISPUTE RESOLUTION</h2>
          <p>
            These Retail Partner T&C and the Contract shall be governed by laws
            of India.
            <br />
            <br />
            The courts of Kolkata shall have exclusive jurisdiction over all
            disputes arising from these Retail Partner T&C and the Contract.
          </p>
          <h2>17. PENALTY</h2>
          <p>
            Notwithstanding anything contrary contained in these Retail Partner
            T&C or the Contract, ETark shall reserve a right to charge a penalty
            in case the service partner is found indulging in fraudulent
            activities while providing Retail Coupon Services. The penalty may
            be deducted from the Retail fee that ETark is to pay to the RP.
          </p>
          <h2>18. MISCELLANEOUS</h2>
          <p>
            (i) Force Majeure: Neither Party shall have any liability under or
            be deemed to be in breach of these Retail Partner T&C or the
            Contract for any delays or failures in performance of these Retail
            Partner T&C and the Contract which results from circumstances beyond
            the reasonable control of that Party such as acts of god, fire,
            epidemic/pandemic, earthquake, tempest, flood, lighting, violence of
            any army or mob or enemies of the country.
            <br />
            <br />
            (ii) Assignment: No rights or liabilities under these Retail Partner
            T&C and the Contract can be assigned by any of the Parties hereto
            without the prior written consent of the other Party.
            <br />
            <br />
            (iii) Entire Contract: These Retail Partner T&C shall be read along
            with the Contract supersedes all prior discussions and Contracts
            (whether oral or written) if any, between the Parties with respect
            to the subject matter of these Retail Partner T&C and the Contract.
            <br />
            <br />
            (iv) Term: These Retail Partner T&C and the Contract shall, unless
            specifically terminated in accordance with the provisions contained
            herein, be valid and effective from the date of the execution of the
            Contract till such time that the Retail Partner continues to remain
            enlisted with the ETark RP Platform.
            <br />
            <br />
            (v) Waiver: No waiver of any part of these Retail Partner T&C and
            the Contract or consent to any departure from it by any Party shall
            be effective unless it is in writing. A waiver or consent shall be
            effective only for the purpose for which it is given. No default or
            delay on the part of any Party in exercising any rights, powers or
            privileges operates as a waiver of any right, nor does a single or
            partial exercise of a right exclude others.
            <br />
            <br />
            (vi) Severance: Any provision of these Retail Partner T&C and the
            Contract which is invalid or unenforceable shall be ineffective to
            the extent of such invalidity or unenforceability, without affecting
            in any way the validity, legality and enforceability of the
            remaining provisions hereof.
            <br />
            <br />
            ETark retains the right to share the information provided by you
            with any financial lending institution(s) if you agree to the same,
            if it is proved within reason that you have availed a loan from
            them. You forego the right to claim any damages from ETark in the
            event any such financial facility has been availed by you. You also
            agree that ETark will not be liable for any damages arising as a
            result of such disclosure of your information. ETark retains the
            right to withhold pending payouts and terminate you on an immediate
            basis in such cases.
            <br />
            <br />
            Retail Partner hereby acknowledges and agrees to the use of his/her
            photographs by ETark for certain purposes, which may include usage
            of the Retail Partner's photographs in ETark's internal
            communications and presentations, training materials, marketing and
            advertising activities on various platforms, including without
            limitation, online advertisement, social media and offline
            advertising. Retail Partner hereby consent to sharing of his/her
            photographs by ETark with third parties for the aforesaid purposes.
            <br />
            <br />
            The information shared by Retail Partner pursuant to this Contract
            shall be used in accordance with the Privacy Policy.
          </p>
          <h2>19. CONFIDENTIALITY</h2>
          <p>
            Other than for provision of Retail Coupon Service by the Service
            Partner, ETark does not share any other information of the Service
            Partner with third parties unless requisitioned by (i) government
            authorities or (ii) the Service Partner, whether orally or in
            writing (via email, SMS etc.) for any purpose whatsoever, including
            but not limited to availing loan from financial institutions, filing
            of tax returns etc.
            <br />
            <br />
            Other than for the purpose of audit between the Manufacturer and the
            Retail Coupon Services, the Retail Partner must not disclose any
            confidential information about ETark, including but not limited to
            these Retail Partner T&C, its business strategies, pricing,
            revenues, expenses, User data, and order information to third
            parties.
          </p>
          <h2>20. DISCLAIMER</h2>
          <p>
            ETark does not warrant that You will be able to use the ETark RP
            Platform and/ or will be able to provide the Retail Coupon Services
            at all times on the ETark RP Platform or that the ETark RP Platform
            and the Platform Services will be uninterrupted or error-free or
            that the defects will be capable of being corrected by the ETark in
            a timely fashion. The User Platform Services, ETark RP Platform, the
            output generated there from, and all other technology developed by
            ETark are provided to you on an “AS IS” and “AS AVAILABLE” basis and
            ETark specifically disclaims all warranties and indemnities,
            express, implied or statutory, including without limitation any
            warranty of merchantability, fitness for a particular purpose,
            accuracy, completeness, or any other warranty arising from the
            course of performance or course of dealing.
          </p>
          <p
            style={{
              marginTop: 20,
              marginBottom: 10
            }}
          >
            ANNEXURE A
          </p>
          <br />
          <br />
          <p className={'annex'}>
            a) Security Deposit: This is a one time interest free refundable fee
            charged by ETark to the Retail Partner applicable on each retail
            outlet that the Retail Partner is On boarding to provision against
            losses that ETark may suffer in future from any direct or indirect
            damages caused by the Retail Partner(subject to the Retail Partner
            Terms and Conditions), the fee of which is prescribed by ETark from
            time to time. Currently this value is zero.
          </p>
          <br />
          <br />
          <p className={'annex'}>
            b) ETark Retail Coupon value : This is the amount that every
            customer of the store has to pay per purchase for specified device
            of specified brand in order to avail ETark Retail Coupon and it
            shall be the responsibility of the Retail Partner to make sure the
            same has been paid by the customer before a Retail Coupon is issued
            to him. Currently this value is Rs 150 (inclusive of all taxes)
          </p>
          <br />
          <br />
          <p className={'annex'}>
            c) ETark Retail Fee : This is the amount that every Retail Partner
            earns from ETark for every Retail Coupon issued to the customer. The
            settlement for the same is done at the end of the month on a post
            paid basis. Currently this value is Rs 20
          </p>
          <br />
          <br />
          <p>
            Retail Partner hereby acknowledges and agrees that any amount
            deposited by Retail Partner to ETark in the form of Security Deposit
            shall stand forfeited at the sole discretion of ETark, in the event
            Retail Partner does not issue at least one ETark Retail Coupon
            pursuant to the Retail Coupon Service under the Contract for a
            continuous period of 30 days during the term of the Contract.
          </p>
        </div>
        <div className={'tncbtn'}>
          <div className={'radiobtn'}>
            <input
              type="checkbox"
              id="tnc"
              name="tnc"
              value="accept"
              onClick={btnenable}
            />
            <label for="tnc">&nbsp;I accept the above Terms & Conditions</label>
          </div>
          <a href="https://forms.gle/t7g7yLUgWExYD5yN7">
            <button id="nextbtn" type="button" disabled="disabled">
              Next
            </button>
          </a>
        </div>
      </div>
    </div>
  );
};

export default bsTerms;
